### ISSUE TITLE
Circular reference when using inheritance & polymorhism with discriminator

### ISSUE THREAD

**Issue by clxandstuff** [openapi-ts/openapi-typescript#1565]
**Description**

Not sure if this is a bug. I would like to confirm that types generation is possible with my schema

```
Typescript definitions are circular which results in "any" types.
```

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `7.0.0` & `6.7.4`                      |
| Node.js              | `18.18.1`                      |
| OS + version         | `macOS 13, Windows 11, etc.` |

**Reproduction**

Generate types with below schema.

```
openapi: 3.0.0
info:
  title: Test schema
  version: V1
paths:
  /resource:
    get:
      operationId: getResource
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PetOwner"
components:
  schemas:
    PetOwner:
      type: object
      properties:
        pet:
          $ref: "#/components/schemas/Pet"
      required:
        - pet
    Pet:
      type: object
      properties:
        petType:
          allOf:
            - $ref: "#/components/schemas/PetType"
          readOnly: true
      discriminator:
        propertyName: petType
        mapping:
          Cat: "#/components/schemas/Cat"
          Dog: "#/components/schemas/Dog"
      oneOf:
        - $ref: "#/components/schemas/Cat"
        - $ref: "#/components/schemas/Dog"
      required:
        - petType
    Cat:
      allOf:
        - $ref: "#/components/schemas/Pet"
        - type: object
          properties:
            name:
              type: string
          required:
            - name
    Dog:
      allOf:
        - $ref: "#/components/schemas/Pet"
        - type: object
          properties:
            bark:
              type: string
          required:
            - bark
    PetType:
      type: string
      enum:
        - Cat
        - Dog
```

It results in:
```
export interface components {
  schemas: {
    PetOwner: {
      pet: components["schemas"]["Pet"];
    };
    Pet: {
      petType: components["schemas"]["PetType"];
    } & (components["schemas"]["Cat"] | components["schemas"]["Dog"]);
    Cat: {
      petType: "Cat";
    } & Omit<components["schemas"]["Pet"], "petType"> & {
      name: string;
    };
    Dog: {
      petType: "Dog";
    } & Omit<components["schemas"]["Pet"], "petType"> & {
      bark: string;
    };
    /** @enum {string} */
    PetType: "Cat" | "Dog";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
```

**Expected result**

I expect Cat & Dog to not reference Pet

```
export interface components {
  schemas: {
    PetOwner: {
      pet: components["schemas"]["Pet"];
    };
    Pet: {
      petType: components["schemas"]["PetType"];
    } & (components["schemas"]["Cat"] | components["schemas"]["Dog"]);
    Cat: {
      petType: "Cat";
    } & {
      name: string;
    };
    Dog: {
      petType: "Dog";
    } & {
      bark: string;
    };
    /** @enum {string} */
    PetType: "Cat" | "Dog";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
```

so I can use types like this
```
import { components } from "./types"

const a = {} as components["schemas"]["PetOwner"];

if (a.pet.petType === 'Cat') {
    a.pet.name
} else {
    a.pet.bark
}
```

Is this possible with the current version? If not I can try to fix this, if you guide me where to start.

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`) - there are some unrelated license and security errors 
- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by clxandstuff** [comment]
I found one more problem.

When changing this:
```
PetOwner:
      type: object
      properties:
        pet:
          # $ref: "#/components/schemas/Pet" - changing to allOf
          allOf:
            - $ref: "#/components/schemas/Pet"
```
generator omit discriminator property "petType"

```
export interface components {
  schemas: {
    PetOwner: {
      pet: {
        petType: "PetOwner";
      } & Omit<components["schemas"]["Pet"], "petType">;
    };
    Pet: {
      petType: components["schemas"]["PetType"];
    } & (components["schemas"]["Cat"] | components["schemas"]["Dog"]);
    Cat: {
      petType: "Cat";
    } & Omit<components["schemas"]["Pet"], "petType"> & {
      name: string;
    };
    Dog: {
      petType: "Dog";
    } & Omit<components["schemas"]["Pet"], "petType"> & {
      bark: string;
    };
    /** @enum {string} */
    PetType: "Cat" | "Dog";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
```

**Comment by clxandstuff** [comment]
@drwpow

Thanks for clarifying all the details. You are right that some parts of the example can cause problems.

I updated the example based on your comments and all looks good, except the case when a discriminator is added.

With this schema:
```
openapi: 3.0.0
info:
  title: Test schema
  version: V1
paths:
  /resource:
    get:
      operationId: getResource
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PetOwner"
components:
  schemas:
    PetOwner:
      type: object
      properties:
        pet:
          allOf:
            - $ref: "#/components/schemas/Pet"
      required:
        - pet
    Pet:
      discriminator:
        propertyName: petType
        mapping:
          Cat: "#/components/schemas/Cat"
          Dog: "#/components/schemas/Dog"
      oneOf:
        - $ref: "#/components/schemas/Cat"
        - $ref: "#/components/schemas/Dog"
    PetCommon:
      type: object
      properties:
        petType:
          allOf:
            - $ref: "#/components/schemas/PetType"
      required:
        - petType
    Cat:
      allOf:
        - $ref: "#/components/schemas/PetCommon"
        - type: object
          properties:
            name:
              type: string
          required:
            - name
    Dog:
      allOf:
        - $ref: "#/components/schemas/PetCommon"
        - type: object
          properties:
            bark:
              type: string
          required:
            - bark
    PetType:
      type: string
      enum:
        - Cat
        - Dog
```

I'm still getting invalid polymorphic "pet" property.
 
```
export interface components {
  schemas: {
    PetOwner: {
      pet: {
        petType: "PetOwner";
      } & Omit<components["schemas"]["Pet"], "petType">;
    };
    Pet: components["schemas"]["Cat"] | components["schemas"]["Dog"];
    PetCommon: {
      petType: components["schemas"]["PetType"];
    };
    Cat: components["schemas"]["PetCommon"] & {
      name: string;
    };
    Dog: components["schemas"]["PetCommon"] & {
      bark: string;
    };
    /** @enum {string} */
    PetType: "Cat" | "Dog";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
```

Discriminator property "petType" is omitted, and replaced with strange value of "PetOwner".

Do you know if I'm still messing with the schema structure?

**Comment by mzronek** [comment]
This will be fixed with this PR: https://github.com/drwpow/openapi-typescript/pull/1578

@drwpow

**Comment by clxandstuff** [comment]
@mzronek 
That's great! Thanks for taking care of this, and waiting for release :)

**Comment by mzronek** [comment]
@clxandstuff Have you tested it with the latest v7 version? Can we close this?

**Comment by clxandstuff** [comment]
Hi @mzronek 

I'm gonna test it today and let you know

**Comment by W2Wizard** [comment]
Stumbled upon this exact issue today. Basically building a Rule Engine with polymorphic self referencing records. (e.g: RuleAnyOf, RuleAllOf, RuleNot, ... Rules within Rules). I personally use Scalar to view my OpenAPI Docs and there it detects the infinite recursion and stops at some point but here it just crashes.

```bash
➜  App.Frontend git:(master) ✗ bun run backend:types
$  openapi-typescript http://backend-api-peeru.dev.localhost:5145/openapi/v1.json -o ./src/lib/api/api.d.ts
✨ openapi-typescript 7.13.0
259 |                 resolvePromises.push(promise);
260 |             }
261 |         }
262 |         async function followRef(document, ref, refStack) {
263 |             if (hasRef(refStack.prev, ref)) {
264 |                 throw new Error('Self-referencing circular pointer');
                                ^
error: Self-referencing circular pointer
      at followRef (/home/wizard/Developer/KKApp/App.Frontend/node_modules/@redocly/openapi-core/lib/resolve.js:264:27)
      at followRef (/home/wizard/Developer/KKApp/App.Frontend/node_modules/@redocly/openapi-core/lib/resolve.js:336:37)

Bun v1.3.11-canary.1+4760d78b3 (Linux x64)
error: script "backend:types" exited with code 1
```

The only fix I have for now is basically as what this guy did: https://github.com/Redocly/redocly-cli/issues/1622 which works fine I basically now have a document transformer to make them first break the circular reference on my backend then monkey patch it to the correct type in my frontend script:

```ts
import { $ } from "bun";

// ============================================================================

const ref = `components["schemas"]["Rule"]`;
const from = "http://backend-api-peeru.dev.localhost:5145/openapi/v1.json";
const to = "./src/lib/api/api.d.ts";

// ============================================================================

console.log("Generating types from OpenAPI spec...");
await $`openapi-typescript ${from} -o ${to}`;
console.log("Patching circular Rule references...");

let source = await Bun.file(to).text();

// AllOfRule / AnyOfRule: rules: Record<string, never>[]  →  rules: Rule[]
source = source.replaceAll(
	"rules: Record<string, never>[]",
	`rules: ${ref}[]`,
);

// NotRule: rule: Record<string, never>  →  rule: Rule
source = source.replaceAll(
	"rule: Record<string, never>",
	`rule: ${ref}`,
);

await Bun.write(to, source);
console.log("Done ✓");
```
