### ISSUE TITLE
TypeError: schemaObject.required?.includes is not a function

### ISSUE THREAD

**Issue by gamell** [openapi-ts/openapi-typescript#1931]
**Description**

Getting `TypeError: schemaObject.required?.includes is not a function` when trying to generate types from a `json` OpenAPI 3.0 spec 

```
joan.gamell@joangamell-MacBook-Pro ~/s/node-sdk (master) [1]> npx openapi-typescript https://docs.moov.io/openapi/openapi.json -o ./lib/_generated-types/types.ts
✨ openapi-typescript 7.4.1
(node:50364) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
file:///Users/joan.gamell/src/node-sdk/node_modules/openapi-typescript/dist/transform/schema-object.js:292
                let optional = schemaObject.required?.includes(k) ||
                                                      ^

TypeError: schemaObject.required?.includes is not a function
    at transformSchemaObjectCore (file:///Users/joan.gamell/src/node-sdk/node_modules/openapi-typescript/dist/transform/schema-object.js:292:55)
    at transformSchemaObjectWithComposition (file:///Users/joan.gamell/src/node-sdk/node_modules/openapi-typescript/dist/transform/schema-object.js:112:28)
    at transformSchemaObject (file:///Users/joan.gamell/src/node-sdk/node_modules/openapi-typescript/dist/transform/schema-object.js:6:18)
    at transformSchemaObjectCore (file:///Users/joan.gamell/src/node-sdk/node_modules/openapi-typescript/dist/transform/schema-object.js:303:23)
    at transformSchemaObjectWithComposition (file:///Users/joan.gamell/src/node-sdk/node_modules/openapi-typescript/dist/transform/schema-object.js:112:28)
    at transformSchemaObject (file:///Users/joan.gamell/src/node-sdk/node_modules/openapi-typescript/dist/transform/schema-object.js:6:18)
    at transformMediaTypeObject (file:///Users/joan.gamell/src/node-sdk/node_modules/openapi-typescript/dist/transform/media-type-object.js:7:12)
    at transformRequestBodyObject (file:///Users/joan.gamell/src/node-sdk/node_modules/openapi-typescript/dist/transform/request-body-object.js:15:15)
    at transformOperationObject (file:///Users/joan.gamell/src/node-sdk/node_modules/openapi-typescript/dist/transform/operation-object.js:13:15)
    at injectOperationObject (file:///Users/joan.gamell/src/node-sdk/node_modules/openapi-typescript/dist/transform/operation-object.js:38:18)

Node.js v22.1.0
```

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `7.4.1`                      |
| Node.js              | `22.1.0`                      |
| OS + version         | `macOS 14.4.1` |

**Reproduction**

`npx openapi-typescript https://docs.moov.io/openapi/openapi.json -o ./lib/_generated-types/types.ts`

**Expected result**

No errors, .ts file generated under `lib/_generated-types`

**Checklist**

- [ ] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by lucasmcht** [comment]
I'm having the same issue, any news on this ?

**Comment by valerijmedvid** [comment]
Same here

**Comment by dkacha** [comment]
I have the same problem with the same Node.js version.

```
(node:15420) [DEP0040] DeprecationWarning: The `punycode` 
module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:399:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:338:10)
    at loadBuiltinModule (node:internal/modules/helpers:114:7)
    at Function._load (node:internal/modules/cjs/loader:1100:17)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)     
    at Object.<anonymous> (D:\Users\992393p\Documents\Modra\foms\node_modules\whatwg-url\lib\url-state-machine.js:2:18)
```

**Comment by dkacha** [comment]
@NDSo  The schemas are correctly. This issue is specific to the Node.js version. It works as expected with Node.js 20.11.1 but does not work with Node.js 22.11.0.

**Comment by valerijmedvid** [comment]
No more errors after the release of the new version [7.6.1](https://github.com/openapi-ts/openapi-typescript/releases/tag/openapi-typescript%407.6.1) with the updated `redocly` library.

**Comment by gzm0** [comment]
Fixed in #2131
